<div class="top-bar">
  <a href="#">
    <img src="https://file.hstatic.net/1000075078/file/vector_706a88566eab4f009bed6eea93cd890b.png" alt="">
    <span>Ho Chi Minh City</span>
  </a>
  <a href="#">
    <img src="https://file.hstatic.net/1000075078/file/group_8de276faa50c486b9d485826c506803b.png" alt="">
    <span>Hotline: 1800.6936</span>
  </a>
  <a href="#">
    <img src="https://file.hstatic.net/1000075078/file/vector_c337310f409d440f890b370ff9cefe44.png" alt="">
    <span>Freeship from $10</span>
  </a>
</div>
<header>
  <nav>
    <a href="index.php"><span class="logo">CoffeeShop.</span></a>
    <ul>
      <li><a href="index.php" <?php echo ($page == "indexPage") ? "class='nav-selected'" : ""; ?> >HOME</a></li>
      <li><a href="about.php" <?php echo ($page == "aboutPage") ? "class='nav-selected'" : ""; ?> >ABOUT</a></li>
      <li><a href="product.php" <?php echo ($page == "productsPage") ? "class='nav-selected'" : ""; ?> >PRODUCTS</a></li>
      <li><a href="payment.php" <?php echo ($page == "enquirePage") ? "class='nav-selected'" : ""; ?> >PAYMENT</a></li>
      <li><a href="manager.php" <?php echo ($page == "managerPage") ? "class='nav-selected'" : ""; ?> >MANAGER</a></li>
      <li><a href="enhancements.php" <?php echo ($page == "enhancements1Page") ? "class='nav-selected'" : ""; ?> >ENCHANCEMENTS</a></li>
      <li><a href="video.php" <?php echo ($page == "videoPage") ? "class='nav-selected'" : ""; ?> >VIDEO</a></li>
    </ul>
  </nav>
</header>
