<?php

    $products = array(
      "Epresso",
      "Cappuccino",
      "Latte",
      "Black Pearl Milk Tea",
      "Peach Orange Lemongrass Tea",
      "Americano",
      "Original Roasted Coffee"
    );

    $product_price = array(
      "Epresso" => 2.50,
      "Cappuccino" => 3.50,
      "Latte" => 3.50,
      "Black Pearl Milk Tea" => 4.50,
      "Peach Orange Lemongrass Tea" => 4.50,
      "Americano" => 3.50,
      "Original Roasted Coffee" => 3.50
    );
    
    $product_img = array(
      "Epresso" => "images/espresso.jpg",
      "Cappuccino" => "images/cappuccino.jpg",
      "Latte" => "images/latte.jpg",
      "Black Pearl Milk Tea" => "images/milk-tea.jpg",
      "Peach Orange Lemongrass Tea" => "images/juice-tea.png",
      "Americano" => "images/americano.jpg",
      "Original Roasted Coffee" => "images/roasted-coffee.jpg"
    );

?>